### ISSUE TITLE
Server 2008R2/2008 Agent crashes on service startup

### ISSUE THREAD

**Issue by russu1993** [Azure/WindowsVMAgent#8]
Version 1010 works fine but 1018 crashes right after the start.

2 Events on a startup of the service:
**.NET Runtime - 1026**
Application: WaAppAgent.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.WindowsAzure.GuestAgent.Core.ServiceInstallFailedException
Stack:
   at Microsoft.WindowsAzure.GuestAgent.TransparentInstaller.GuestAgentInstallerThread.<Start>b__46_0()
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Application Error - 1000**
Name der fehlerhaften Anwendung: WaAppAgent.exe, Version: 2.7.41491.1018, Zeitstempel: 0x60f1fdae
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 6.1.7601.24499, Zeitstempel: 0x5d0115f1
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000000b87d
ID des fehlerhaften Prozesses: 0x26e0
Startzeit der fehlerhaften Anwendung: 0x01d78a01d2076560
Pfad der fehlerhaften Anwendung: C:\WindowsAzure\Packages_202185_155650\WaAppAgent.exe
Pfad des fehlerhaften Moduls: C:\Windows\system32\KERNELBASE.dll
Berichtskennung: 1ad4792e-f5f5-11eb-9e13-000d3aaf3be2

**Comment by Aymendje** [comment]
Thank you for the report. We will investigate this issue.
Is it always crashing for you, or only on the first start ?
Are you using a Custom image, or marketplace ?

**Comment by russu1993** [comment]
> Thank you for the report. We will investigate this issue.
> Is it always crashing for you, or only on the first start ? - Crashes every time on start of the guest agent service 
> Are you using a Custom image, or marketplace ? - VM was migrated via ASR from on-prem Hyper-V infrastructure, so i would say custom.

**Comment by Aymendje** [comment]
Can you email me at aydjella@microsoft.com with your VM details ? (Name, Resource group, subscription, etc.)
I will raise an internal case and we will follow up on this
Thank you !

**Comment by enindee** [comment]
Same happened to me. Latest VM agent that works is 2.7.41491.1010. With any newer VM agent service won't start.

**Comment by roviracarlos** [comment]
The same happened to me with Marketplace VMs with Windows 2008 R2 SP1 deployed with ARMTemplates.
I have a template that does join domain after the deployment and always fails to contact the agent, only on this OS, for others works well.

**Comment by Aymendje** [comment]
Thank you for the reports.
This is now a known issue and we already are working on a fix.
Hotfix deployment will start this week.
The issue seems to be happening only in older windows version, due to some command line parsing.

**Comment by Aymendje** [comment]
Hotfix deployment started : https://github.com/Azure/WindowsVMAgent/releases/tag/2.7.41491.1028
